version: '3.1'
services:
  # my-app: 
  #   image: registry.gitlab.com/d7705/docker-test/my-app:1.0
  #   ports: 
  #     - 3000:3000
  mongodb-container:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pasword
    volumes:
      - mongo-data:/data/db
  mongo-express-container:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pasword
      - ME_CONFIG_MONGODB_SERVER=mongodb-container
volumes:
  mongo-data:
    driver: local
